### ISSUE TITLE
prescreen error

### ISSUE THREAD

**Issue by Bobo22331** [liusy-jz/MODAS#1]
Hi, when I run the prescreen step:
```
MODAS.py prescreen -g ../genotype/chr_HAMP -genome_cluster ./chr_HAMP.genome_cluster.csv -phe ../metabolome/E3_log2.normalized_phe.csv -p 20 -o E3_log2
```
It occurs the error:
```
Thu May 13 17:10:14 2021: begin phenotype prescreen analysis...
Thu May 13 17:10:14 2021: Read phenotype file finished,There are 735 phenotypes in phenotype file.
Thu May 13 17:10:59 2021: convert genome cluster file to bimbam genotype file.
Thu May 13 17:11:16 2021: run lm model for genome cluster pseudo-SNP filter.
Traceback (most recent call last):
  File "/home/cuixb/tools/biosoft/conda3/envs/modas/bin/MODAS.py", line 4, in <module>
    __import__('pkg_resources').run_script('MODAS==1.0', 'MODAS.py')
  File "/home/cuixb/tools/biosoft/conda3/envs/modas/lib/python3.7/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/cuixb/tools/biosoft/conda3/envs/modas/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/home/cuixb/tools/biosoft/conda3/envs/modas/lib/python3.7/site-packages/MODAS-1.0-py3.7.egg/EGG-INFO/scripts/MODAS.py", line 470, in <module>
  File "/home/cuixb/tools/biosoft/conda3/envs/modas/lib/python3.7/site-packages/MODAS-1.0-py3.7.egg/EGG-INFO/scripts/MODAS.py", line 389, in MODAS
  File "/home/cuixb/tools/biosoft/conda3/envs/modas/lib/python3.7/site-packages/MODAS-1.0-py3.7.egg/EGG-INFO/scripts/MODAS.py", line 191, in prescreen
  File "/home/cuixb/tools/biosoft/conda3/envs/modas/lib/python3.7/site-packages/MODAS-1.0-py3.7.egg/modas/prescreen.py", line 31, in generate_omics_qtl_pc_bimbam
    gwas = pd.read_csv('output/'+phe.replace('m/z','m.z')+'_bimbam_lm.assoc.txt',sep='\t')
  File "/home/cuixb/tools/biosoft/conda3/envs/modas/lib/python3.7/site-packages/pandas-1.2.4-py3.7-linux-x86_64.egg/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/cuixb/tools/biosoft/conda3/envs/modas/lib/python3.7/site-packages/pandas-1.2.4-py3.7-linux-x86_64.egg/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/cuixb/tools/biosoft/conda3/envs/modas/lib/python3.7/site-packages/pandas-1.2.4-py3.7-linux-x86_64.egg/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/cuixb/tools/biosoft/conda3/envs/modas/lib/python3.7/site-packages/pandas-1.2.4-py3.7-linux-x86_64.egg/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/cuixb/tools/biosoft/conda3/envs/modas/lib/python3.7/site-packages/pandas-1.2.4-py3.7-linux-x86_64.egg/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/home/cuixb/tools/biosoft/conda3/envs/modas/lib/python3.7/site-packages/pandas-1.2.4-py3.7-linux-x86_64.egg/pandas/io/parsers.py", line 1368, in _open_handles
    storage_options=kwds.get("storage_options", None),
  File "/home/cuixb/tools/biosoft/conda3/envs/modas/lib/python3.7/site-packages/pandas-1.2.4-py3.7-linux-x86_64.egg/pandas/io/common.py", line 647, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'output/n0004_bimbam_lm.assoc.txt'
```
So, how to solve this?
Thank you!

**Comment by liusy-jz** [comment]
Can you check whether the 'output/n0004_bimbam_lm.assoc.txt' file exists ?

**Comment by Bobo22331** [comment]
It doesn't exist. This file is generated by prescreen?

**Comment by liusy-jz** [comment]
yes, it's generated by prescreen command. can you type gemma.linux in terminal to check whether gemma software is exists, if gemma software is not exists, please show me your linux $PATH variable.

**Comment by Bobo22331** [comment]
Ok, maybe I didn't install gemma software. I'll check it again. Thank you!

**Comment by liusy-jz** [comment]
You don't need to install gemma, I put gemma software in MODAS utils folder,  You just need to check whether the utils folder is in your  $PATH variable and whether gemma can run normally.

**Comment by Bobo22331** [comment]
Ok, got it.
