### ISSUE TITLE
Error occurred when I ran genoidx

### ISSUE THREAD

**Issue by Sh1ne111** [liusy-jz/MODAS#4]
Hi, 

An error occurred when I ran genoidx. Can you help me solve this problem?

Regards,

chens

/public/home/chens/software/miniconda3/envs/R/bin/MODAS.py genoidx -g test -clump -genome_cluster -o test
Tue Nov 14 10:15:55 2023: begin snp clumping...
Traceback (most recent call last):
  File "/public/home/chens/software/miniconda3/envs/R/bin/MODAS.py", line 4, in <module>
    __import__('pkg_resources').run_script('MODAS==1.0', 'MODAS.py')
  File "/public/home/chens/software/miniconda3/envs/R/lib/python3.10/site-packages/pkg_resources/__init__.py", line 722, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/public/home/chens/software/miniconda3/envs/R/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1572, in run_script
    exec(script_code, namespace, namespace)
  File "/public/home/chens/software/miniconda3/envs/R/lib/python3.10/site-packages/MODAS-1.0-py3.10.egg/EGG-INFO/scripts/MODAS.py", line 510, in <module>
  File "/public/home/chens/software/miniconda3/envs/R/lib/python3.10/site-packages/MODAS-1.0-py3.10.egg/EGG-INFO/scripts/MODAS.py", line 419, in MODAS
  File "/public/home/chens/software/miniconda3/envs/R/lib/python3.10/site-packages/MODAS-1.0-py3.10.egg/EGG-INFO/scripts/MODAS.py", line 77, in genoidx
  File "/public/home/chens/software/miniconda3/envs/R/lib/python3.10/site-packages/MODAS-1.0-py3.10.egg/modas/genoidx.py", line 211, in snp_clumping
    snp_keep = bigsnpr.snp_clumping(g[0], infos_chr=g[2]['chromosome'], infos_pos=g[2]['physical.pos'],
  File "/public/home/chens/software/miniconda3/envs/R/lib/python3.10/site-packages/rpy2/robjects/vectors.py", line 1363, in __getitem__
    tmp = rinterface.ListSexpVector.__getitem__(self, i)
  File "/public/home/chens/software/miniconda3/envs/R/lib/python3.10/site-packages/rpy2/rinterface_lib/sexp.py", line 643, in __getitem__
    raise TypeError(
TypeError: Indices must be integers or slices, not <class 'str'>

**Comment by liusy-jz** [comment]
Is your genotype file in plink bed format?

**Comment by Sh1ne111** [comment]
> Is your genotype file in plink bed format?

Thanks for your reply, I have resolved the error!
